//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.activity;

import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.text.Html;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import org.voxe.android.R.id;
import org.voxe.android.R.layout;
import org.voxe.android.R.string;
import org.voxe.android.common.ShareManager_;

public final class AboutActivity_
    extends AboutActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.about);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        shareVoxeContent = resources_.getString(string.share_voxe_content);
        shareManager = ShareManager_.getInstance_(this);
    }

    private void afterSetContentView_() {
        descriptionTextView = ((TextView) findViewById(id.descriptionTextView));
        if (descriptionTextView!= null) {
            descriptionTextView.setText(Html.fromHtml(this.getString(string.about_content)));
        }
        {
            View view = findViewById(id.rate_android_market);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AboutActivity_.this.rateAndroidMarketClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.share_voxe);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AboutActivity_.this.shareVoxeClicked();
                    }

                }
                );
            }
        }
        ((ShareManager_) shareManager).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static AboutActivity_.IntentBuilder_ intent(Context context) {
        return new AboutActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AboutActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AboutActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
