//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.activity;

import java.io.Serializable;
import java.util.HashSet;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.webkit.WebView;
import android.widget.ImageView;
import android.widget.TextView;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.actionbarsherlock.view.MenuItem;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import org.voxe.android.R.layout;
import org.voxe.android.R.string;
import org.voxe.android.VoxeApplication;
import org.voxe.android.common.Analytics_;
import org.voxe.android.common.ComparisonWebviewClient_;

public final class ComparisonActivity_
    extends ComparisonActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.comparison);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        comparisonWebviewLoadingMessage = resources_.getString(string.comparison_webview_loading_message);
        shareCompare = resources_.getString(string.share_compare);
        injectExtras_();
        application = ((VoxeApplication) this.getApplication());
        webviewClient = ComparisonWebviewClient_.getInstance_(this);
        analytics = Analytics_.getInstance_(this);
    }

    private void afterSetContentView_() {
        candidate1ImageView = ((ImageView) findViewById(org.voxe.android.R.id.candidate1ImageView));
        loading = ((TextView) findViewById(org.voxe.android.R.id.loading));
        candidate2ImageView = ((ImageView) findViewById(org.voxe.android.R.id.candidate2ImageView));
        webview = ((WebView) findViewById(org.voxe.android.R.id.webview));
        ((ComparisonWebviewClient_) webviewClient).afterSetContentView_();
        ((Analytics_) analytics).afterSetContentView_();
        initLayout();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ComparisonActivity_.IntentBuilder_ intent(Context context) {
        return new ComparisonActivity_.IntentBuilder_(context);
    }

    @SuppressWarnings("unchecked")
    private<T >T cast_(Object object) {
        return ((T) object);
    }

    private void injectExtras_() {
        Intent intent_ = getIntent();
        Bundle extras_ = intent_.getExtras();
        if (extras_!= null) {
            if (extras_.containsKey("selectedTagId")) {
                try {
                    selectedTagId = cast_(extras_.get("selectedTagId"));
                } catch (ClassCastException e) {
                    Log.e("ComparisonActivity_", "Could not cast extra to expected type, the field is left to its default value", e);
                }
            }
            if (extras_.containsKey("selectedCandidateIds")) {
                try {
                    selectedCandidateIds = cast_(extras_.get("selectedCandidateIds"));
                } catch (ClassCastException e) {
                    Log.e("ComparisonActivity_", "Could not cast extra to expected type, the field is left to its default value", e);
                }
            }
            if (extras_.containsKey("electionIndex")) {
                try {
                    electionIndex = ((Integer) extras_.get("electionIndex"));
                } catch (ClassCastException e) {
                    Log.e("ComparisonActivity_", "Could not cast extra to expected type, the field is left to its default value", e);
                }
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getSupportMenuInflater();
        menuInflater.inflate(org.voxe.android.R.menu.compare, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        switch (item.getItemId()) {
            case android.R.id.home:
                homeSelected();
                return true;
            default:
                return false;
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ComparisonActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ComparisonActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public ComparisonActivity_.IntentBuilder_ selectedTagId(String selectedTagId) {
            intent_.putExtra("selectedTagId", selectedTagId);
            return this;
        }

        public ComparisonActivity_.IntentBuilder_ selectedCandidateIds(HashSet<String> selectedCandidateIds) {
            intent_.putExtra("selectedCandidateIds", ((Serializable) selectedCandidateIds));
            return this;
        }

        public ComparisonActivity_.IntentBuilder_ electionIndex(int electionIndex) {
            intent_.putExtra("electionIndex", electionIndex);
            return this;
        }

    }

}
