//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.activity;

import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.text.Html;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import org.voxe.android.R.id;
import org.voxe.android.R.layout;
import org.voxe.android.R.string;
import org.voxe.android.VoxeApplication;

public final class LoadingActivity_
    extends LoadingActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.loading);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        voxeOrgTitle = Html.fromHtml(resources_.getString(string.voxe_org_title));
        application = ((VoxeApplication) this.getApplication());
    }

    private void afterSetContentView_() {
        downloadingProgressBar = ((ProgressBar) findViewById(id.downloadingProgressBar));
        downloadingText = ((TextView) findViewById(id.downloadingText));
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static LoadingActivity_.IntentBuilder_ intent(Context context) {
        return new LoadingActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, LoadingActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public LoadingActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
