//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.activity;

import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.text.Html;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.actionbarsherlock.view.MenuItem;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import org.voxe.android.R.layout;
import org.voxe.android.R.string;
import org.voxe.android.VoxeApplication;
import org.voxe.android.adapter.ElectionAdapter_;
import org.voxe.android.common.Analytics_;

public final class SelectElectionActivity_
    extends SelectElectionActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.select_elections_list);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        voxeOrgTitle = Html.fromHtml(resources_.getString(string.voxe_org_title));
        application = ((VoxeApplication) this.getApplication());
        adapter = ElectionAdapter_.getInstance_(this);
        analytics = Analytics_.getInstance_(this);
    }

    private void afterSetContentView_() {
        listView = ((ListView) findViewById(org.voxe.android.R.id.listView));
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(org.voxe.android.R.id.listView));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        listViewItemClicked(position);
                    }

                }
                );
            }
        }
        ((ElectionAdapter_) adapter).afterSetContentView_();
        ((Analytics_) analytics).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static SelectElectionActivity_.IntentBuilder_ intent(Context context) {
        return new SelectElectionActivity_.IntentBuilder_(context);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getSupportMenuInflater();
        menuInflater.inflate(org.voxe.android.R.menu.select_election, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        switch (item.getItemId()) {
            case org.voxe.android.R.id.about:
                aboutSelected();
                return true;
            case org.voxe.android.R.id.refresh:
                refreshSelected();
                return true;
            default:
                return false;
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelectElectionActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelectElectionActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
