//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.activity;

import java.util.HashSet;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import com.actionbarsherlock.view.MenuItem;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import org.voxe.android.R.layout;
import org.voxe.android.VoxeApplication;
import org.voxe.android.adapter.SelectCandidatesAdapter_;
import org.voxe.android.common.Analytics_;

public final class SelectCandidatesActivity_
    extends SelectCandidatesActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.select_candidates_list);
    }

    private void init_(Bundle savedInstanceState) {
        injectExtras_();
        application = ((VoxeApplication) this.getApplication());
        analytics = Analytics_.getInstance_(this);
        adapter = SelectCandidatesAdapter_.getInstance_(this);
        restoreSavedInstanceState_(savedInstanceState);
    }

    private void afterSetContentView_() {
        listView = ((ListView) findViewById(org.voxe.android.R.id.listView));
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(org.voxe.android.R.id.listView));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        listViewItemClicked(position);
                    }

                }
                );
            }
        }
        ((Analytics_) analytics).afterSetContentView_();
        ((SelectCandidatesAdapter_) adapter).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static SelectCandidatesActivity_.IntentBuilder_ intent(Context context) {
        return new SelectCandidatesActivity_.IntentBuilder_(context);
    }

    private void injectExtras_() {
        Intent intent_ = getIntent();
        Bundle extras_ = intent_.getExtras();
        if (extras_!= null) {
            if (extras_.containsKey("electionIndex")) {
                try {
                    electionIndex = ((Integer) extras_.get("electionIndex"));
                } catch (ClassCastException e) {
                    Log.e("SelectCandidatesActivity_", "Could not cast extra to expected type, the field is left to its default value", e);
                }
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        switch (item.getItemId()) {
            case android.R.id.home:
                homeSelected();
                return true;
            default:
                return false;
        }
    }

    @Override
    public void onSaveInstanceState(Bundle bundle) {
        super.onSaveInstanceState(bundle);
        bundle.putSerializable("selectedCandidateIds", selectedCandidateIds);
    }

    @SuppressWarnings("unchecked")
    private void restoreSavedInstanceState_(Bundle savedInstanceState) {
        if (savedInstanceState == null) {
            return ;
        }
        selectedCandidateIds = ((HashSet<String> ) savedInstanceState.getSerializable("selectedCandidateIds"));
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelectCandidatesActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelectCandidatesActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public SelectCandidatesActivity_.IntentBuilder_ electionIndex(int electionIndex) {
            intent_.putExtra("electionIndex", electionIndex);
            return this;
        }

    }

}
