//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.data;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.client.ClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

public class ElectionResourceClient_
    implements ElectionResourceClient
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public ElectionResourceClient_() {
        restTemplate = new RestTemplate();
        rootUrl = "http://voxe.org/api/v1";
    }

    public ElectionResourceClient_(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    public ElectionResourceClient_(ClientHttpRequestFactory requestFactory) {
        restTemplate = new RestTemplate(requestFactory);
    }

    @Override
    public RestTemplate getRestTemplate() {
        return restTemplate;
    }

    @Override
    public void setRestTemplate(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    @Override
    public ElectionResponse getElections() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/elections/search"), HttpMethod.GET, requestEntity, ElectionResponse.class).getBody();
    }

}
