//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.common;

import android.app.Activity;
import android.content.Context;
import android.content.res.Resources;
import android.text.Html;
import android.view.View;
import org.voxe.android.R.string;

public final class AboutDialogHelper_
    extends AboutDialogHelper
{

    private Context context_;

    private AboutDialogHelper_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((ShareManager_) shareManager).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        Resources resources_ = context_.getResources();
        shareVoxeContent = resources_.getString(string.share_voxe_content);
        aboutContent = Html.fromHtml(resources_.getString(string.about_content));
        context = context_;
        shareManager = ShareManager_.getInstance_(context_);
    }

    public static AboutDialogHelper_ getInstance_(Context context) {
        return new AboutDialogHelper_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
