//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.common;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import org.voxe.android.activity.ComparisonActivity;

public final class ComparisonWebviewClient_
    extends ComparisonWebviewClient
{

    private Context context_;

    private ComparisonWebviewClient_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        if (context_ instanceof ComparisonActivity) {
            activity = ((ComparisonActivity) context_);
        }
    }

    public static ComparisonWebviewClient_ getInstance_(Context context) {
        return new ComparisonWebviewClient_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
