//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.voxe.android.common;

import android.app.Activity;
import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import org.voxe.android.R.string;

public final class ShareManager_
    extends ShareManager
{

    private Context context_;

    private ShareManager_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        Resources resources_ = context_.getResources();
        shareWith = resources_.getString(string.share_with);
        context = context_;
    }

    public static ShareManager_ getInstance_(Context context) {
        return new ShareManager_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
